### ISSUE TITLE
Error Message: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by Andy8r0X** [littleplus/Bilibili-Album-Download#1]
下載特定ID遇到錯誤，錯誤為 _Error Message: 'float' object cannot be interpreted as an integer_
修正方法將第95行else部分增加int
`	totalPage = int(totalDraw/30)+1 if totalDraw % 30 != 0 else int(totalDraw/30)`

**Comment by littleplus** [comment]
请问能附加一下具体的ID吗，以便我这边复现

**Comment by Andy8r0X** [comment]
在這個ID `492393`，當時第一篇是這篇 [https://t.bilibili.com/370998725274583293?tab=2](https://t.bilibili.com/370998725274583293?tab=2) 遇到錯誤，其他ID都能直接順利下載，只有這ID立刻出現錯誤，修正後即可順利下載。

**Comment by littleplus** [comment]
不好意思，我这边直到所有相簿都下载完也未能复现这个bug，关于这篇
```
https://h.bilibili.com/64870834
```
的实际图片文件：
![image](https://user-images.githubusercontent.com/11694750/77831628-503f8180-716b-11ea-9189-6bcd64ebb627.png)
也可以正常下载下来。

下载完成后，总共
![image](https://user-images.githubusercontent.com/11694750/77831657-77964e80-716b-11ea-9302-74f2c4b6c930.png)

请问你本地用的python版本是多少呢，有对代码除了你说的修改以外，有其他修改吗？希望最好能截个图，谢谢

**Comment by Andy8r0X** [comment]
版本是Python 3.5.4，除了該行修改以外沒有修改其他部分，當時沒有截圖所以也無法上傳到這裡。

**Comment by littleplus** [comment]
哈哈，根据和朋友的聊天，总算找到了问题，已经改用函数去取整了
